language: go
go:
  - "1.10"

before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app:
    master: ppl-auth-dev
    release: ppl-auth